//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeterKrausAP05LAP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderLine = new HashSet<OrderLine>();
        }
        public Order(Customer kunde, decimal totalPrice)
        {
            CustomerId = kunde.Id;
            PriceTotal = null;
            DateOrdered = DateTime.Now;
            Zip = kunde.Zip;
            City = kunde.City;
            FirstName = kunde.FirstName;
            LastName = kunde.LastName;
            this.OrderLine = new HashSet<OrderLine>();

        }

        public int Id { get; set; }
        public int CustomerId { get; set; }
        public Nullable<decimal> PriceTotal { get; set; }
        public System.DateTime DateOrdered { get; set; }
        public string Zip { get; set; }
        public string City { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderLine> OrderLine { get; set; }
    }
}
